apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-fastapi-app
spec:
  selector:
    matchLabels:
      app: your-fastapi-app
  replicas: 3
  template:
    metadata:
      labels:
        app: your-fastapi-app
    spec:
      containers:
      - name: your-fastapi-app
        image: your-account-id.dkr.ecr.your-region.amazonaws.com/your-repository-name:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "2048Gi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
            add: ["NET_BIND_SERVICE"] # Add the necessary capabilities here
